
```{r}
library(gtools)
library(ggplot2)
library(ggsci)
library(tidyverse)
rm(list=ls())
filename <- "Merge Y O worm OMI.csv"
NSCdata_rawtitle <- paste('C:/Users/cmorc/OneDrive - Harvard University/Projects/OMI/Merge aging n1 2 3 omi worm/',filename, sep = "")
NSCdata_raw <- read.csv(NSCdata_rawtitle)
NSCdatacyto <- subset(NSCdata_raw, celltype=="cyto")
mygroups <- c("Y","O")
NSCdatacontrol <- subset(NSCdatacyto, Group%in%mygroups)
NSCdatacontrol$Group <- factor(NSCdatacontrol$Group, levels=c("Y","O"))
NSCdata <- NSCdatacontrol

colorA <- "darkblue" 
colorQ <- "red" 
plotcolors <- c(colorA, colorQ)
plotcolors

##normalize data set##
myvars <- c("n.a1.mean", "n.t1.mean", "n.t2.mean", "n.tm.mean", "Group")
NSCdata_reduc <- NSCdatacontrol[myvars]
last <- ncol(NSCdata_reduc)
range01 <- function(x){(x-min(x))/(max(x)-min(x))}
NSCdata_reduc_norm <- range01(NSCdata_reduc[,-last])
Group <- NSCdatacontrol$Group
NSCdata_reduc_norm_Group <- data.frame(NSCdata_reduc_norm, Group)
set.seed(1)
```
##tSNE##
```{r}
library(Rtsne)
set.seed(1)
tsne <- Rtsne(NSCdata_reduc_norm_Group[,-last], dims=2, perplexity = 10, verbose=TRUE,max_iter=1000)
colors = rainbow(length(unique(NSCdata_reduc_norm_Group$Group)))
names(colors) = unique(NSCdata_reduc_norm_Group$Group)
par(mar=c(5,7,1,1), mgp=c(4,1,0), pty="s")
plot(tsne$Y[,1], tsne$Y[,2], pch=16, xlab="tSNE 1", ylab="tSNE 2", "cex.lab"=1, "cex.axis"=1, las=1, col=c(colorA, colorQ)[as.numeric(NSCdata_reduc_norm_Group$Group)])
legend(x=8, y=33, legend=c("Young", "Old"), pch=16, col=plotcolors, lwd=4, seg.len=0, bty="n", cex=, pt.cex=1) 
```
##LogisticRegression##
```{r}
library(pROC) 
library(randomForest)
justnada1 <- subset(NSCdata_reduc_norm_Group, select = c(n.a1.mean))
justnadt1 <- subset(NSCdata_reduc_norm_Group, select = c(n.t1.mean))
justnadt2 <- subset(NSCdata_reduc_norm_Group, select = c(n.t2.mean))

rfmodelall <- glm(Group ~ ., data=NSCdata_reduc_norm_Group, family=binomial)

rfmodeljusta1 <- glm(Group ~ ., data=justnada1, family=binomial)
rfmodeljustt1 <- glm(Group ~ ., data=justnadt1, family=binomial)
rfmodeljustt2 <- glm(Group ~ ., data=justnadt2, family=binomial)

rocmodelall <- roc(NSCdata_reduc_norm_Group$Group, rfmodelall$fitted.values, plot=FALSE)

rocmodela1 <- roc(NSCdata_reduc_norm_Group$Group, rfmodeljusta1$fitted.values, plot=FALSE)
rocmodelt1 <- roc(NSCdata_reduc_norm_Group$Group, rfmodeljustt1$fitted.values, plot=FALSE)
rocmodelt2 <- roc(NSCdata_reduc_norm_Group$Group, rfmodeljustt2$fitted.values, plot=FALSE)


par(mar=c(4, 4, 4, 4), mgp=c(4,1,0), pty="s")
  roc(NSCdata_reduc_norm_Group$Group, rfmodelall$fitted.values, col="red", print.auc=TRUE, print.auc.x=0.3, print.auc.y=0.2, plot=TRUE, "cex.lab"=1, "cex.axis"=1, las=1)
plot.roc(rocmodela1, rfmodeljusta1$fitted.values, col="purple", print.auc=TRUE, print.auc.x=0.3, print.auc.y=0.15, add=TRUE, plot=TRUE)
plot.roc(rocmodelt1, rfmodeljustt1$fitted.values, col="blue", print.auc=TRUE, print.auc.x=0.3, print.auc.y=0.1, add=TRUE, plot=TRUE)
plot.roc(rocmodelt2, rfmodeljustt2$fitted.values, col="green", print.auc=TRUE, print.auc.x=0.3, print.auc.y=0.05, add=TRUE, plot=TRUE)




```







